### ISSUE TITLE
Possible Refactor: Reduce Duplication and Abc complexity by using a data structure for steam games

### ISSUE THREAD

**Issue by pachonk** [Mingosio/mingos.py#3]
https://github.com/Mingosio/mingos.py/blob/master/get-games.py#L57-L120
And also below, the data is exactly the same except the relationship between game session and steam_id, so the huge refactor you could do is put that into a data structure like a [dictionary](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)

```python
MINGOS_GAME_ID_STEAM_ID_MAPPING = {
    2: 252950,
    3: 274940
}
```

Then 90% of that if elif goes away and it looks something like this (not sure python syntax):
```python
mingos_id = gamesession["game"]["id"]
steam_id = MINGOS_GAME_ID_STEAM_ID_MAPPING[mingos_id]
fullurl = steamurl + str(steam_id)
```
Which reduces the duplication and should make the file about half the size and 100% more readable

**Comment by awurster1** [comment]
I attempted your changes but had issues with getting this error "SyntaxError: unindent does not match any outer indentation level" which I've narrowed down to a tab/spacing issue, but I'm having issues resolving it, so until I can get past it, I'm stuck.

**Comment by awurster1** [comment]
The get-games file is still in the original format just to make it easy to switch back

**Comment by pachonk** [comment]
Git makes reverts super trivial, see "git revert" docs
Also, for experimental pushes I highly recommend branching to a different
branch, because then master will remain intact.

**Comment by pachonk** [comment]
Toss the dict at the top as a constant and see if you still have issues
maybe.

**Comment by d4rkd0s** [comment]
@awurster1 Just so you totally understand git, I would avoid those GUIs like SourceTree as they fail to teach what's actually occurring underneath. The `git` cli is pretty powerful and takes 10-15 minutes to learn: https://try.github.io/levels/1/challenges/1

You'll feel like you upgraded a Lvl 1 Dagger to a Lvl 100 Sword once you jump to the cli.

**Comment by d4rkd0s** [comment]
Also I +1 the branching, it's just good habit to branch and test out / build out a new feature on a feature branch.

This is your repo, as the Python Team lead. So you can structure as you wish / see fit. However here is a recommendation for branching called GitFlow:  https://datasift.github.io/gitflow/IntroducingGitFlow.html

**Comment by pachonk** [comment]
@d4rkd0s I actually like "GitHub flow" more than git flow

**Comment by pachonk** [comment]
Again, structured as per team lead. I just figured I'd put in my 2 cents
about git flow

**Comment by pachonk** [comment]
https://guides.github.com/introduction/flow/
The core difference from the original Atlassian git flow is that it cuts
out the develop branch and it relies heavier on PR flow

**Comment by pachonk** [comment]
Fixed in https://github.com/Mingosio/mingos.py/commit/203f3708b39158457b4b19575ba115951e6d2be7
